// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy0DkXZ9PtyWhTVBCZbpGsGfVFtavZPEc',
    appId: '1:894231968109:web:814adb70b736afb3bfc264',
    messagingSenderId: '894231968109',
    projectId: 'my-app-288br',
    authDomain: 'my-app-288br.firebaseapp.com',
    storageBucket: 'my-app-288br.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH7cG41EXfwD6OkxY6cg_W8MSFl5QZ2pM',
    appId: '1:894231968109:android:2782488c069e1e38bfc264',
    messagingSenderId: '894231968109',
    projectId: 'my-app-288br',
    storageBucket: 'my-app-288br.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy0DkXZ9PtyWhTVBCZbpGsGfVFtavZPEc',
    appId: '1:894231968109:web:29d25364860810e7bfc264',
    messagingSenderId: '894231968109',
    projectId: 'my-app-288br',
    authDomain: 'my-app-288br.firebaseapp.com',
    storageBucket: 'my-app-288br.firebasestorage.app',
  );
}
